name: diabetes_and_me
description: A diabetes-friendly lifestyle tracking app.
version: 1.0.0+1

environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0 
  fluttertoast: ^8.2.12
  flutter_secure_storage: ^6.0.0
  uuid: ^3.0.6
  intl: ^0.18.1
  mobile_scanner: ^3.5.6
  supabase_flutter: ^2.3.4
  uni_links: ^0.5.1  # More stable for deep linking

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Add assets configuration - points to frontend/assets/ directory
  assets:
    - assets/
  
  # Optional: Configure app icon
  # You can use flutter_launcher_icons package to generate all sizes
  # flutter_icons:
  #   android: true
  #   ios: true
  #   image_path: "assets/appicon.png"